### PR TITLE
Fixed package names 

### PR DESCRIPTION
**Pull request by lfoppiano**
HI Patrice, 
   I've found some disalighment in the package names, which I've corrected it. 

Cheers
Luca

### CODE REVIEW

**Comment by kermitt2** [comment]
Hi! The idea is _not_ to have a org.grobid.ner package, similarly as for grobid-quantities and the other grobid "extensions". Is it creating a problem?

**Comment by lfoppiano** [comment]
OK, there is no problem. In the grobid-ner [directory structure ](https://github.com/kermitt2/grobid-ner/tree/master/grobid-ner/src/main/java/org/grobid/ner)there is a 'ner' directory. To maintain the 
consistency it should be removed, in order to match the `package` directive.

**Comment by kermitt2** [comment]
Ah yes now I remember - you have already told me ;)
In grobid-quantities, we modified the directory structure, not the package names. I guess we should do the same here (and I will have to update other grobid additional stuff similarly).

**Comment by lfoppiano** [comment]
👍

**Pull request closed without merging**
